name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:  [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build the Docker image
      # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        run: docker build -t flask-app:latest .
    # CD
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: pppopuchang
          password: dckr_pat_JtRo3u2yjGIcuE8Fd_NNgq64vno
      - name: image ID
        run: docker images
      - name: image tag
        run: docker tag flask-app:latest pppopuchang/flask-app:latest
      - name: Push the Docker image
        # docker tag 118a648f6ce9 pppopuchang/flask-app:latest
        run: docker push pppopuchang/flask-app:latest